[workspace]
resolver = "2"
members = ["admin",
    "client",
    "server", 
    "shared",
]

[workspace.package]
edition = "2024"
version = "0.2.0"
license = "MIT"

[workspace.dependencies]
serde = {version = "1.0.229", features = ["derive"]}
serde_json = "1.0.151"
eframe = "0.36.2"
axum = "0.8.9"
reqwest = { version = "0.13.5", features = ["json", "blocking"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"